### PR TITLE
Update lib/app/helpers/respond_helper.rb

### PR DESCRIPTION
**Pull request by andycroll**
attributes incorrect on respond-proxy.html

### CODE REVIEW

**Comment by laurens** [comment]
+1

**Comment by qnm** [comment]
Hi @gevans - are you still maintaining this library? It's still useful, but a little out of date!

**Comment by gevans** [comment]
@qnm I've more recently been using https://rails-assets.org/ to fulfill the need of external javascript dependencies. They're more up-to-date and are better maintained. Otherwise, yes. This project definitely needs a maintainer.

**Comment by qnm** [comment]
@gevans I like the helpers provided by the library, and I'm likely to deploy this to a production project, so I'm happy to maintain it if you no longer wish to do so.

**Pull request closed without merging**
